name: Build/release

on:
    push:
        branches:
            - main
            - master
            - updater

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    # - windows-latest # Skip windows for now to figure out canvas dependencies

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install npm build dependencies
              run: npm i --no-save electron-builder electron-builder-notarize

            - name: Install canvas dependencies (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

            - name: Install canvas dependencies (macOS)
              if: startsWith(matrix.os, 'macos')
              run: brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman

            - name: Prepare for app notarization
              if: startsWith(matrix.os, 'macos')
              # Import Apple API key for app notarization on macOS
              run: |
                  mkdir -p ~/private_keys/
                  echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
            - name: Install Xcode Tools
              if: startsWith(matrix.os, 'macos')
              run: |
                  sudo xcodebuild -license accept

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1.6.0
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
              env:
                  DEBUG: "electron-builder"

            - name: Check for notarization-error.log
              if: failure()
              run: |
                  if [ -f notarization-error.log ]; then
                    echo "Notarization log found:"
                    cat notarization-error.log
                  else
                    echo "Notarization log not found."
                  fi
