name: Build/release

on:
    push:
        tags: [v*]

permissions:
    contents: write # Required for creating releases

jobs:
    build-and-release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - macos-13 # x86 (Intel) macOS
                    - ubuntu-latest
                    - windows-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 20

            - name: Install Snapcraft (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo snap install snapcraft --classic

            - name: Prepare for app notarization
              if: startsWith(matrix.os, 'macos')
              run: |
                  mkdir -p ~/private_keys/
                  echo '${{ secrets.apple_api_key }}' > ~/private_keys/apple_api_key.p8

            - name: Check if build passes without errors
              uses: OpenMarch/builder@v5
              with:
                  release: false
                  github_token: ${{ secrets.github_token }}
