name: Build

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 22

            - name: Install canvas dependencies (macOS)
              if: startsWith(matrix.os, 'macos')
              run: brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman python-setuptools

            - name: Install canvas dependencies (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

            - name: Set up Wine for Windows build (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install -y \
                    software-properties-common \
                    wine64 \
                    wine32 \
                    winbind \
                    xvfb
                  # Verify Wine installation
                  wine --version

            - name: Build/release Electron app
              uses: OpenMarch/builder@v2
              with:
                  release: false
                  github_token: ${{ secrets.github_token }}
