name: Test Build

on:
    pull_request:
        branches: [main, develop, prerelease/*]

permissions:
    contents: write # Required for creating releases

jobs:
    test-build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - macos-13 # x86 (Intel) macOS
                    - ubuntu-latest
                    - windows-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install Snapcraft (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo snap install snapcraft --classic

            - name: Check if build passes without errors
              uses: OpenMarch/builder@v5
              with:
                  release: false
                  github_token: ${{ secrets.github_token }}
