name: Format

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install project dependencies
              run: npm ci
            - name: Format
              run: npm run prettier
