name: Lint

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js and pnpm
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"
            - name: Install project dependencies
              run: pnpm install --frozen-lockfile
            - name: Lint
              run: pnpm run lint
