name: Lint

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v4
            - name: Install canvas dependencies
              run: sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
            - name: Install project dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
