name: Publish node.js Packages

on:
    push:
        branches: ["main", "internal-packages"]
        tags: [v*]

jobs:
    # Switch to the changeset action once we normalize this
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0

            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
            - run: pnpm install
            - run: pnpm test

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
