name: Spellcheck

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install canvas dependencies
              run: sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
            - name: Install project dependencies
              run: npm ci
            - name: Spellcheck
              run: npm run spellcheck
