name: Test

on:
    pull_request:
        branches: [main, develop, prerelease/*]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - branch: main
                      artifact: main
                    - branch: ${{ github.head_ref }}
                      artifact: pull-request

        permissions:
            # Required to checkout the code
            contents: read

        steps:
            - uses: actions/checkout@v4
            - name: Install project dependencies
              run: npm ci
            - name: Install canvas dependencies
              run: npm install canvas
            - name: Test Prepare
              run: npm run test:prepare
            - name: Test
              run: npm run test:coverage
            - name: "Upload Coverage"
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.artifact }}
                  path: coverage
